name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/hugalittle_c_usr/data/www/hugalittle.com/hug_a_little
            git checkout main && git fetch --all && git reset --hard origin/main
            git pull origin main

            # yarn install --production --frozen-lockfile
            # yarn build
            # pm2 restart process.json --env production

